### ISSUE TITLE
Doesnt' work on my Mac or Linux

### ISSUE THREAD

**Issue by bbarclay** [weaveworks/wks-quickstart-firekube#92]
/Users/bbarclay/wks-quickstart-firekube/setup.js:105
const sshPort = machine => machine.ports.find(p => p.guest == 22).host;
                                         ^
TypeError: Cannot read property 'find' of null
    at sshPort (/Users/bbarclay/wks-quickstart-firekube/setup.js:105:42)
    at /Users/bbarclay/wks-quickstart-firekube/setup.js:115:16
Module (setup.js) has not been loaded

My docker ps on the mac doesn't work now.

In linux the error was 

command "ignite run weaveworks/ignite-centos:firekube-pre3 --name=firekube-node0 --cpus=2 --memory=1GB --size=5GB --kernel-image=weaveworks/ignite-kernel:4.19.47 --ssh=/var/www/laradock/wks-quickstart-firekube/cluster-key.pub --ports=2222:22 --ports=6443:6443 --ports=30443:30443 --ports=30080:30080" exited with "time=\"2020-12-23T08:13:28Z\" level=info msg=\"containerd image \\\"weaveworks/ignite-centos:firekube-pre3\\\" not found locally, pulling...\"\ntime=\"2020-12-23T08:14:16Z\" level=info msg=\"Starting image import...\"\ntime=\"2020-12-23T08:14:41Z\" level=info msg=\"Imported OCI image \\\"weaveworks/ignite-centos:firekube-pre3\\\" (1.6 GB) to base image with UID \\\"756cc53de5a0c781\\\"\"\ntime=\"2020-12-23T08:14:41Z\" level=info msg=\"containerd image \\\"weaveworks/ignite-kernel:4.19.47\\\" not found locally, pulling...\"\ntime=\"2020-12-23T08:14:45Z\" level=info msg=\"Imported OCI image \\\"weaveworks/ignite-kernel:4.19.47\\\" (49.6 MB) to kernel image with UID \\\"9414cdaba181972c\\\"\"\ntime=\"2020-12-23T08:14:46Z\" level=info msg=\"Created VM with ID \\\"f265e346fe62fdf7\\\" and name \\\"firekube-node0\\\"\"\ntime=\"2020-12-23T08:14:46Z\" level=fatal msg=\"[ERROR ExistingFile--dev-kvm]: File /dev/kvm, does not exist\\n[ERROR ExistingFile--opt-cni-bin-bridge]: File /opt/cni/bin/bridge, does not exist\\n\"\n": exit status 1

**Comment by chanwit** [comment]
> File /dev/kvm, does not exist
It seems you don't have KVM installed on your Linux box.
You can check about this by running:

`sudo kvm-ok`

**Comment by harin7602** [comment]
I too have same issue in MAC.

<img width="915" alt="Screen Shot 2021-05-11 at 23 37 13" src="https://user-images.githubusercontent.com/31981869/118011739-0402d100-b36e-11eb-93e3-ec2a63dd9d91.png">
<img width="607" alt="Screen Shot 2021-05-11 at 23 37 37" src="https://user-images.githubusercontent.com/31981869/118011769-0c5b0c00-b36e-11eb-8209-ba84dc7034aa.png">

**Comment by harin7602** [comment]
> I too have same issue in MAC.
> 
> <img alt="Screen Shot 2021-05-11 at 23 37 13" width="915" src="https://user-images.githubusercontent.com/31981869/118011739-0402d100-b36e-11eb-93e3-ec2a63dd9d91.png">
> 
> <img alt="Screen Shot 2021-05-11 at 23 37 37" width="607" src="https://user-images.githubusercontent.com/31981869/118011769-0c5b0c00-b36e-11eb-8209-ba84dc7034aa.png">

This issue was solved once I disabled the kubernetes in Docker Desktop for MAC

**Comment by dkdndes** [comment]
On a minimal Debian11, I needed to install "kvm" and "dnsmasq" and needed to make sure that "dnsmasq" is running/started; after this, it all worked. 

However, it would be helpful to add additional checks within "setup.sh"; this could prevent the failure of setup.js (which is started within "setup.sh", and requires on a Linux host the presence of "kvm" and a running "dnsmasq."
